name: Test Builds
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: GraalVM setup
      uses: graalvm/setup-graalvm@v1
      with:
          version: '22.3.0'
          java-version: '19'
          components: 'native-image'
    - name: setup jextract
      run: |
        wget https://download.java.net/java/early_access/jextract/2/openjdk-19-jextract+2-3_linux-x64_bin.tar.gz;
        tar -xvf openjdk-19-jextract+2-3_linux-x64_bin.tar.gz;
        echo "`pwd`/jextract-19/bin" >> $GITHUB_PATH;
        ls `pwd`/jextract-19/bin;
        jextract --help;
    - name: Build with Maven
      run: mvn clean package
